### ISSUE TITLE
[TODO] Add functionality to Graphics and Audio

### ISSUE THREAD

**Issue by CensedPie** [Newtonius/HackingGame#15]
Add functionality to Graphics and Audio
#Graphics
- [ ] Add resolution change
- [ ] Add windowed, borderless, fullscreen options
- [ ] Add msaa option?
#Audio
- [ ] Add music slider
- [ ] Add sound effects slider
